### ISSUE TITLE
Conform BirdBush to Codable only when its wrapped type is Codable

### ISSUE THREAD

**Issue by ZevEisenberg** [hsnetzer/bird-bush#3]
You might be able to find some good uses of conditional conformance here: https://github.com/davecom/SwiftGraph

Something like:

```swift
extension BirdBush: Codable where U: Codable {
    // I forget if the compiler will do the work for you, or if you’ll have to write the conformance yourself
}
```

**Comment by hsnetzer** [comment]
Thanks for the suggestion, Zev.

**Comment by ZevEisenberg** [comment]
Hey, @hsnetzer,

There’s a subtle issue with the way this is implemented now: `BirdBush` only exists where `U` is `Codable`, which effectively comes to the same problem as before: you can’t use it except with `Codable` types. I think you want something like this:

```swift
class BirdBush<U> {
    ...
}

extension BirdBush: Codable where U: Codable {
    ...
}
```

This way, you can use BirdBush with any type you want, and if you happen to use it with a `Codable` type, it will become `Codable` automatically. You can read more about conditional conformance here: https://swift.org/blog/conditional-conformance/

Enjoy 😉

**Comment by hsnetzer** [comment]
Ah, thanks again! the where clause would probably cause an error when initializing with anything but codable types. I’ll fix this tomorrow.

**Comment by hsnetzer** [comment]
a3b1db0591d7214cbc42e58aa790d63b39a46d47

This implements the conditional conformance we want. As a consequence of adding conformance in an extension, I did have to mark BirdBush as final, which I'm fine with. Otherwise child objects might [not actually be codable](https://forums.swift.org/t/why-you-cant-make-someone-elses-class-decodable-a-long-winded-explanation-of-required-initializers/6437).
